# app/models.py
# =============================================================================
# RespiraCare-ICU — All Pydantic data models
# Every object that crosses an API boundary or moves between modules is defined
# here. Import from this file everywhere — never define models inline elsewhere.
# =============================================================================

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Literal
from pydantic import BaseModel, Field


# =============================================================================
# ENUMS
# =============================================================================

class PatientState(str, Enum):
    """
    The complete set of states a ventilated ICU patient can be in.
    Transitions are governed by patient.py (apply_action + advance_hour).
    """
    INTUBATED_UNSTABLE    = "INTUBATED_UNSTABLE"     # On full vent, physiologically unstable
    INTUBATED_STABLE      = "INTUBATED_STABLE"        # On full vent, stable, may be weaning candidate
    SBT_IN_PROGRESS       = "SBT_IN_PROGRESS"         # Spontaneous breathing trial underway
    READY_TO_EXTUBATE     = "READY_TO_EXTUBATE"       # SBT passed, awaiting extubation order
    EXTUBATED             = "EXTUBATED"               # Tube removed, breathing independently
    INTUBATED_WITH_VAP    = "INTUBATED_WITH_VAP"      # On vent, has developed VAP infection
    REINTUBATED           = "REINTUBATED"             # Was extubated, failed, back on vent
    DISCHARGED            = "DISCHARGED"              # Left ICU — bed is free


class SupportLevel(str, Enum):
    """
    What type of respiratory support device the patient is currently on.
    """
    FULL_VENTILATOR = "FULL_VENTILATOR"   # Invasive mechanical ventilation
    BIPAP           = "BIPAP"             # Non-invasive bilevel positive airway pressure
    HFNC            = "HFNC"             # High-flow nasal cannula
    ROOM_AIR        = "ROOM_AIR"         # No respiratory support — fully independent


class AlarmType(str, Enum):
    """
    The clinical type of alarm being generated by a patient's monitoring equipment.
    """
    SPO2_LOW       = "spo2_low"        # Blood oxygen saturation below threshold
    HR_HIGH        = "hr_high"         # Heart rate too high
    RR_HIGH        = "rr_high"         # Respiratory rate too high
    PEAK_PRESSURE  = "peak_pressure"   # Peak inspiratory pressure alarm
    LOW_TIDAL_VOL  = "low_tidal_vol"   # Tidal volume too low
    APNEA          = "apnea"           # No breathing detected
    BATTERY        = "battery"         # Power / equipment alarm


class Severity(str, Enum):
    """
    Categorical severity band for a patient — used by patient_generator.py.
    """
    LOW    = "low"      # Stable, near extubation-ready
    MEDIUM = "medium"   # Improving, may be a weaning candidate
    HIGH   = "high"     # Unstable, high VAP risk, resource-intensive


class ActionType(str, Enum):
    """
    All valid actions the agent can take on a patient in a single step.
    Matches the Action.action_type field exactly.
    """
    ATTEMPT_SBT           = "attempt_sbt"
    EXTUBATE              = "extubate"
    STEP_DOWN_TO_BIPAP    = "step_down_to_bipap"
    STEP_DOWN_TO_HFNC     = "step_down_to_hfnc"
    ESCALATE_TO_FULL_VENT = "escalate_to_full_vent"
    ASSIGN_RT_ATTENTION   = "assign_rt_attention"
    ENFORCE_VAP_BUNDLE    = "enforce_vap_bundle"
    RESPOND_TO_ALARM      = "respond_to_alarm"
    SUPPRESS_ALARM        = "suppress_alarm"
    HOLD_AND_MONITOR      = "hold_and_monitor"
    ETHICAL_TRIAGE_SELECT = "ethical_triage_select"


# =============================================================================
# PER-PATIENT OBSERVATION
# What the agent sees about a single patient at each step.
# =============================================================================

class PatientObservation(BaseModel):
    """
    The agent-visible snapshot of a single patient's clinical state.
    All fields reflect what a Charge RT would see on the bedside monitor
    and chart — no hidden internal state is exposed here.
    """
    patient_id: str = Field(
        ...,
        description="Unique patient identifier within the episode, e.g. 'P01'"
    )
    state: PatientState = Field(
        ...,
        description="Current clinical state of the patient"
    )
    support_level: SupportLevel = Field(
        ...,
        description="What respiratory support device the patient is currently on"
    )
    severity: Severity = Field(
        ...,
        description="Overall acuity band — LOW / MEDIUM / HIGH"
    )

    # --- Weaning readiness vitals ---
    rsbi: Optional[float] = Field(
        None,
        description="Rapid Shallow Breathing Index. <105 needed for SBT. None if on BiPAP/HFNC."
    )
    pf_ratio: Optional[float] = Field(
        None,
        description="PaO2/FiO2 ratio. >200 required for SBT eligibility."
    )
    rass: Optional[float] = Field(
        None,
        description="Richmond Agitation-Sedation Scale. Must be -2 to 0 for weaning."
    )
    fio2: float = Field(
        ...,
        description="Fraction of inspired oxygen (0.21 = room air, 1.0 = 100% O2)"
    )
    peep: float = Field(
        ...,
        description="Positive End-Expiratory Pressure in cmH2O"
    )
    spo2: float = Field(
        ...,
        description="Peripheral oxygen saturation as a percentage"
    )
    heart_rate: float = Field(
        ...,
        description="Heart rate in beats per minute"
    )
    resp_rate: float = Field(
        ...,
        description="Respiratory rate in breaths per minute"
    )
    hemodynamically_stable: bool = Field(
        ...,
        description="True if patient is not on vasopressors and has acceptable BP"
    )

    # --- Ventilator duration ---
    hours_on_vent: int = Field(
        ...,
        description="Total cumulative hours the patient has been mechanically ventilated"
    )
    sbt_passed_within_hours: Optional[int] = Field(
        None,
        description="Hours since the last successful SBT. None if no SBT has been passed."
    )

    # --- Risk scores ---
    sofa_score: int = Field(
        ...,
        ge=0, le=24,
        description="SOFA score (0-24). Lower = better prognosis. Used in ethical triage."
    )
    reintubation_risk: float = Field(
        ...,
        ge=0.0, le=1.0,
        description="Model-estimated probability of reintubation if extubated now"
    )
    vap_risk: float = Field(
        ...,
        ge=0.0, le=1.0,
        description="Cumulative VAP infection risk. >0.70 triggers infection event."
    )

    # --- VAP prevention tracking ---
    vap_bundle_compliance_hours: int = Field(
        ...,
        description="Hours in this episode that VAP bundle was enforced for this patient"
    )
    hours_since_last_bundle: int = Field(
        ...,
        description="Hours since enforce_vap_bundle was last applied to this patient"
    )

    # --- Handover degradation flag ---
    observation_degraded: bool = Field(
        False,
        description="True when handover is in progress and some vitals may be approximate"
    )


# =============================================================================
# ALARM EVENT
# =============================================================================

class AlarmEvent(BaseModel):
    """
    A single alarm in the ward's active alarm feed.
    The agent does not know whether an alarm is real or a false positive —
    that is exactly what it must learn to distinguish.
    """
    alarm_id: str = Field(
        ...,
        description="Unique alarm identifier within the episode"
    )
    patient_id: str = Field(
        ...,
        description="Which patient triggered this alarm"
    )
    alarm_type: AlarmType = Field(
        ...,
        description="Clinical type of alarm"
    )
    hour_generated: int = Field(
        ...,
        description="Shift hour at which this alarm was first generated"
    )
    consecutive_same_type: int = Field(
        0,
        description="How many consecutive alarms of this type this patient has generated"
    )
    # NOTE: is_real is intentionally NOT exposed in this model.
    # The grader accesses it separately through the internal alarm store.


# =============================================================================
# INCOMING PATIENT ALERT
# =============================================================================

class IncomingAlert(BaseModel):
    """
    Advance warning of a patient being transferred into the ICU.
    The agent must plan equipment availability before arrival.
    """
    alert_id: str = Field(
        ...,
        description="Unique alert identifier"
    )
    eta_hours: int = Field(
        ...,
        description="Hours until this patient arrives and needs a bed/ventilator"
    )
    support_needed: SupportLevel = Field(
        ...,
        description="What level of respiratory support this incoming patient will require"
    )
    sofa_estimate: Optional[int] = Field(
        None,
        description="Estimated SOFA score of incoming patient if known (e.g. from referral notes)"
    )
    severity_estimate: Severity = Field(
        ...,
        description="Estimated severity of the incoming patient"
    )


# =============================================================================
# ETHICAL TRIAGE CASE
# =============================================================================

class EthicalTriageCase(BaseModel):
    """
    Presented to the agent when two patients simultaneously need a ventilator
    and only one can be freed. The agent must use ethical_triage_select.
    The grader checks the decision against the SOFA-based framework.
    """
    case_id: str = Field(
        ...,
        description="Unique identifier for this triage event"
    )
    patient_a_id: str = Field(
        ...,
        description="First patient competing for the resource"
    )
    patient_b_id: str = Field(
        ...,
        description="Second patient competing for the resource"
    )
    patient_a_sofa: int = Field(
        ...,
        ge=0, le=24,
        description="SOFA score of patient A"
    )
    patient_b_sofa: int = Field(
        ...,
        ge=0, le=24,
        description="SOFA score of patient B"
    )
    patient_a_wait_hours: int = Field(
        ...,
        description="How many hours patient A has been waiting for a ventilator"
    )
    patient_b_wait_hours: int = Field(
        ...,
        description="How many hours patient B has been waiting for a ventilator"
    )
    resource_type: SupportLevel = Field(
        ...,
        description="Which resource is being allocated (usually FULL_VENTILATOR)"
    )


# =============================================================================
# FULL WARD OBSERVATION (what the agent receives each step)
# =============================================================================

class Observation(BaseModel):
    """
    The complete observation returned by reset() and after each step().
    This is what the agent sees at the start of every decision cycle.
    """
    # --- Episode metadata ---
    episode_id: str = Field(
        ...,
        description="Unique identifier for this episode"
    )
    task_id: int = Field(
        ...,
        description="Which task is being run (1, 2, or 3)"
    )
    shift_hour: int = Field(
        ...,
        ge=0,
        description="Current hour of the 12-hour shift (0 = start of shift)"
    )

    # --- Ward-level resource state ---
    available_ventilators: int = Field(
        ...,
        ge=0,
        description="Number of free full mechanical ventilators right now"
    )
    available_bipap: int = Field(
        ...,
        ge=0,
        description="Number of free BiPAP units right now"
    )
    available_hfnc: int = Field(
        ...,
        ge=0,
        description="Number of free HFNC units right now"
    )
    available_rts: int = Field(
        ...,
        ge=0,
        description="Number of respiratory therapists available this hour"
    )

    # --- Patient list ---
    patients: List[PatientObservation] = Field(
        ...,
        description="One PatientObservation per patient currently in the ward"
    )

    # --- Alarm feed ---
    active_alarms: List[AlarmEvent] = Field(
        default_factory=list,
        description="All active alarms in the ward this hour"
    )

    # --- Incoming patient announcements ---
    incoming_patients: List[IncomingAlert] = Field(
        default_factory=list,
        description="Pre-announced incoming patients with ETA"
    )

    # --- Special flags ---
    handover_degraded: bool = Field(
        False,
        description="True during hour 6 — observation quality is reduced for some patients"
    )
    triage_decision_required: Optional[EthicalTriageCase] = Field(
        None,
        description="Present only when the agent must make an ethical triage decision this step"
    )


# =============================================================================
# ACTION (what the agent sends each step)
# =============================================================================

class Action(BaseModel):
    """
    A single action targeting a single patient.
    The agent sends a list of Actions (one per patient) each step.
    """
    patient_id: str = Field(
        ...,
        description="Which patient this action targets"
    )
    action_type: ActionType = Field(
        ...,
        description="What the agent is doing to/for this patient"
    )
    priority: int = Field(
        2,
        ge=1, le=3,
        description="Priority 1 (urgent) to 3 (routine). Used when RT resources are constrained."
    )
    ethical_triage_patient_id: Optional[str] = Field(
        None,
        description="Only required when action_type is ETHICAL_TRIAGE_SELECT. "
                    "The ID of the patient being allocated the scarce resource."
    )


class StepAction(BaseModel):
    """
    The full payload the agent sends to POST /step.
    Contains one Action per patient in the ward.
    """
    session_id: str = Field(
        ...,
        description="Session ID returned by POST /reset"
    )
    actions: List[Action] = Field(
        ...,
        description="One action per patient. Patients not mentioned receive hold_and_monitor."
    )


# =============================================================================
# REWARD BREAKDOWN
# =============================================================================

class RewardBreakdown(BaseModel):
    """
    Per-component reward breakdown for a single step.
    Returned in EpisodeResponse.info so the grader can inspect individual signals.
    """
    total: float = Field(
        ...,
        description="Sum of all reward components for this step"
    )

    # Positive components
    extubation_reward: float = Field(0.0)
    equipment_freed_reward: float = Field(0.0)
    sbt_reward: float = Field(0.0)
    vap_bundle_reward: float = Field(0.0)
    rt_assignment_reward: float = Field(0.0)
    alarm_true_positive_reward: float = Field(0.0)
    alarm_false_negative_reward: float = Field(0.0)  # correctly suppressing false alarms
    ethical_triage_reward: float = Field(0.0)

    # Penalty components
    reintubation_penalty: float = Field(0.0)
    no_vent_available_penalty: float = Field(0.0)
    vap_develops_penalty: float = Field(0.0)
    bipap_deterioration_penalty: float = Field(0.0)
    rt_misallocation_penalty: float = Field(0.0)
    alarm_missed_penalty: float = Field(0.0)
    alarm_false_escalation_penalty: float = Field(0.0)
    ethical_triage_penalty: float = Field(0.0)


# =============================================================================
# EPISODE RESPONSE (what the server returns after each step)
# =============================================================================

class EpisodeResponse(BaseModel):
    """
    The full response from POST /step.
    Matches the OpenEnv standard: observation + reward + done + info.
    """
    observation: Observation = Field(
        ...,
        description="The new ward state after applying the agent's actions"
    )
    reward: float = Field(
        ...,
        description="Total scalar reward for this step (sum of all per-patient rewards)"
    )
    done: bool = Field(
        ...,
        description="True when the episode has ended (shift_hour reached task max_hours)"
    )
    info: dict = Field(
        default_factory=dict,
        description="Additional information: reward breakdown, crisis events, grader signals"
    )


# =============================================================================
# RESET RESPONSE (what the server returns from POST /reset)
# =============================================================================

class ResetResponse(BaseModel):
    """
    The response from POST /reset.
    Gives the agent its session ID and the initial observation.
    """
    session_id: str = Field(
        ...,
        description="UUID the agent must include in every subsequent request header"
    )
    observation: Observation = Field(
        ...,
        description="Initial ward state at the start of the episode"
    )
    task_description: str = Field(
        ...,
        description="Plain-English description of what the agent must accomplish this episode"
    )


# =============================================================================
# INTERNAL ALARM RECORD (not exposed to agent — used by grader)
# =============================================================================

class InternalAlarmRecord(BaseModel):
    """
    The full alarm record kept internally by the alarm_fatigue module.
    The is_real field is hidden from the agent's AlarmEvent but accessible
    to the grader for scoring alarm response accuracy.
    """
    alarm_id: str
    patient_id: str
    alarm_type: AlarmType
    hour_generated: int
    is_real: bool                           # The ground truth — hidden from agent
    consecutive_same_type: int
    agent_responded: Optional[bool] = None  # Set when agent acts on this alarm
    hour_responded: Optional[int] = None


# =============================================================================
# INTERNAL VAP RECORD (not exposed to agent — used by grader)
# =============================================================================

class PendingVAPEvent(BaseModel):
    """
    Queued VAP infection event. When vap_risk crosses the threshold,
    the infection is recorded here and fires after VAP_ONSET_DELAY_HOURS.
    """
    patient_id: str
    risk_at_trigger: float
    trigger_hour: int
    onset_hour: int       # = trigger_hour + VAP_ONSET_DELAY_HOURS
    fired: bool = False